version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dragonbound
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_private_network

networks:
  my_private_network:
    driver: bridge

volumes:
  mysql_data:
