services:
  mysql:
    # image: mysql:5.7
    image: mysql:8.0
    container_name: mysql_dragonbound
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dragonbound
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/dragonbound.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_private_network
  game:
    build:
      context: .
      dockerfile: game.Dockerfile
    container_name: game_dragonbound
    volumes:
      - ./src/game:/app/src/game
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    networks:
      - my_private_network
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: web_dragonbound
    volumes:
      - ./src/web:/app/src/web
    ports:
      - "80:80"
    depends_on:
      - mysql
      - game
    networks:
      - my_private_network

networks:
  my_private_network:
    driver: bridge

volumes:
  mysql_data:
